" Vim with all enhancements
source $VIMRUNTIME/vimrc_example.vim

set guioptions -=T
set guioptions -=m

set number
set shiftwidth=4
set tabstop=4
set smarttab
syntax on

set noundofile

set pastetoggle=

set noswapfile
set nobackup
set nowb

set spell spelllang=en

let g:codestats_api_key = 'KEY'

set hlsearch
set incsearch

set fencs=utf-8,cp1251,koi8-r,cp866
set fileformat=unix

set rtp+=$HOME/_vim/bundle/Vundle.vim/
call vundle#begin('$HOME/_vim/bundle/')

Plugin 'vbe0201/vimdiscord'
Plugin 'https://gitlab.com/code-stats/code-stats-vim.git' 
Plugin 'ycm-core/YouCompleteMe'
Plugin 'vim-syntastic/syntastic.git'
Plugin 'terryma/vim-multiple-cursors' 
Plugin 'w0rp/ale' 
Plugin 'jiangmiao/auto-pairs' 
Plugin 'scrooloose/nerdtree.git' 
Plugin 'VundleVim/Vundle.vim' 

call vundle#end()
filetype plugin indent on

" Use the internal diff if available.
" Otherwise use the special 'diffexpr' for Windows.
if &diffopt !~# 'internal'
  set diffexpr=MyDiff()
endif
function MyDiff()
  let opt = '-a --binary '
  if &diffopt =~ 'icase' | let opt = opt . '-i ' | endif
  if &diffopt =~ 'iwhite' | let opt = opt . '-b ' | endif
  let arg1 = v:fname_in
  if arg1 =~ ' ' | let arg1 = '"' . arg1 . '"' | endif
  let arg1 = substitute(arg1, '!', '\!', 'g')
  let arg2 = v:fname_new
  if arg2 =~ ' ' | let arg2 = '"' . arg2 . '"' | endif
  let arg2 = substitute(arg2, '!', '\!', 'g')
  let arg3 = v:fname_out
  if arg3 =~ ' ' | let arg3 = '"' . arg3 . '"' | endif
  let arg3 = substitute(arg3, '!', '\!', 'g')
  if $VIMRUNTIME =~ ' '
    if &sh =~ '\<cmd'
      if empty(&shellxquote)
        let l:shxq_sav = ''
        set shellxquote&
      endif
      let cmd = '"' . $VIMRUNTIME . '\diff"'
    else
      let cmd = substitute($VIMRUNTIME, ' ', '" ', '') . '\diff"'
    endif
  else
    let cmd = $VIMRUNTIME . '\diff'
  endif
  let cmd = substitute(cmd, '!', '\!', 'g')
  silent execute '!' . cmd . ' ' . opt . arg1 . ' ' . arg2 . ' > ' . arg3
  if exists('l:shxq_sav')
    let &shellxquote=l:shxq_sav
  endif
endfunction

